### ISSUE TITLE
Not working in FF 7 or 8 

### ISSUE THREAD

**Issue by subrb** [cracell/s3bear#4]
After selecting files to upload, users are getting "undefined" in the progress bar.

**Comment by cracell** [comment]
Seems to be an issue with http://code.google.com/p/jquery-html5-upload/source/browse/trunk/example.html due to changes to the File Reader https://developer.mozilla.org/en/DOM/FileReader

**Comment by cracell** [comment]
Here's the issue on the jquery-html5-upload http://code.google.com/p/jquery-html5-upload/issues/detail?id=23&can=1

No one has addressed it yet.

**Comment by cracell** [comment]
Fixed with version 0.3.0.
